### PR TITLE
Upstep aws_ping and support for newer wildfly.

### LINKED ISSUE #2: Only works in Wildfly 10
I understand that this module was intended for Wildfly 10 (judging by some cursory google searches), but it should be explicitly stated somewhere in the README. Trying to use this module in Wildfly 9 results in some issues, and requires an older version of the AWS SDK (due to changes in the apache-httpcomponents library).

### PR DESCRIPTION
**Pull request by steven-aerts**
I think this also fixes #2.

### CODE REVIEW

**Comment by blajoie55** [comment]
What's the status of this PR? Just wondering why it's been open for so long and not yet merged to main/upstream soulwing project. FWIW, I've forked this repo, build, deployed, and tested this fix on an AWS elastic beanstalk keycloak 4.8.2 (wildfly 13) instance and confirmed it fixed the issue with AWS_PING:

```
java.lang.NoSuchMethodError: org.jgroups.util.UUID.get(Lorg/jgroups/Address;)Ljava/lang/String;
at com.meltmedia.jgroups.aws.AWS_PING.findMembers(AWS_PING.java:324)
```

**Comment by ceharris** [comment]
Just because I get so many Github notifications that I sometimes miss the important ones.  :-(

**Comment by blajoie55** [comment]
Thanks Carl. Do you plan on doing another release soon?

**Comment by ceharris** [comment]
The release build is running right now. After it finishes, I'll create a new release on GitHub, and it'll hit Maven Central in a few hours.

**Comment by ceharris** [comment]
And... done!  Release 1.0.5.

**Pull request merged**
